[font]
size = 13

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[window]
padding = { x = 24, y = 24 }
decorations = "Full" # Changed from "Transparent" to a valid option
opacity = 0.9
level = "Normal"
option_as_alt = "Both"

[cursor]
unfocused_hollow = true
style = { shape = "Block", blinking = "On" }
blink_interval = 800
# If you want the cursor to never blink:
# blink_interval = 0

[keyboard]
bindings = [
{ key = "A", mods = "Option|Shift", action = "SpawnNewInstance" },
# Tabs don't seem to work on Linux.
{ key = "T", mods = "Option|Shift", action = "CreateNewTab" },
{ key = "R", mods = "Option|Shift", action = "SelectNextTab" },
{ key = "Y", mods = "Option|Shift", action = "SelectPreviousTab" },
{ key = "1", mods = "Option|Shift", action = "SelectTab1" },
{ key = "2", mods = "Option|Shift", action = "SelectTab2" },
{ key = "3", mods = "Option|Shift", action = "SelectTab3" },
{ key = "4", mods = "Option|Shift", action = "SelectTab4" },
{ key = "5", mods = "Option|Shift", action = "SelectTab5" },
{ key = "6", mods = "Option|Shift", action = "SelectTab6" },
{ key = "7", mods = "Option|Shift", action = "SelectTab7" },
{ key = "8", mods = "Option|Shift", action = "SelectTab8" },
{ key = "9", mods = "Option|Shift", action = "SelectTab9" },
{ key = "U", mods = "Option|Shift", action = "SelectLastTab" },

# -- Don't understand these. They might not work. ---
# { key = "L", mods = "Option|Super", action = "ToggleLineSelection" },
# { key = "B", mods = "Option|Super", action = "ToggleBlockSelection" },
# { key = "O", mods = "Option|Super", action = "Open" },

# -- CreateNewWindow seems to do a tab on MacOS and a separate window on Linux --
{ key = "N", mods = "Option|Shift", action = "CreateNewWindow" },

# Navigate word-by-word to right or left by holding Option (or Alt) + Left/Right arrows
{ key = "Left",  mods = "Alt", chars = "\u001bb", mode = "~Vi" },
{ key = "Right", mods = "Alt", chars = "\u001bf", mode = "~Vi" },
# ..and additionally hold Shift to select/deselect to the left/right
#{ key = "Left",  mods = "Alt|Shift", chars = "\u001b[1;4D" },
#{ key = "Right", mods = "Alt|Shift", chars = "\u001b[1;4C" },
{ key = "Left", mods = "Alt|Shift", action = "ToggleSemanticSelection", mode = "Vi" },
{ key = "Right", mods = "Alt|Shift", action = "ToggleSemanticSelection", mode = "Vi" }
]

# color scheme pasted from Tokyo Night theme
# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_night.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'
